-- Profiles
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text,
  phone text,
  matricula text,
  role text,
  sector text,
  photo_url text,
  appearance jsonb,
  language text,
  email text,
  updated_at timestamptz
);

-- Financial Records
create table if not exists financial_records (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  category text,
  value numeric,
  date date,
  attachment text,
  observation text,
  record_type text not null, -- 'fixedCosts', 'variableCosts', 'revenues', 'receivables'
  client text, -- for revenue/receivable
  due_date date, -- for receivable
  status text, -- 'pending', 'paid' for receivable
  created_at timestamptz default now()
);

-- Calendar Events
create table if not exists calendar_events (
  id bigint generated by default as identity primary key,
  description text,
  value numeric,
  due_date date,
  status text, -- 'pending', 'completed'
  completion_date date,
  reminder_minutes int,
  color text,
  justification text,
  created_at timestamptz default now()
);

-- Vehicles
create table if not exists vehicles (
  id text primary key,
  plate text,
  model text,
  year int,
  driver text,
  status text,
  created_at timestamptz default now()
);

-- Maintenance Tasks
create table if not exists maintenance_tasks (
  id text primary key,
  vehicle_id text,
  service_type text,
  date date,
  cost numeric,
  notes text,
  status text,
  created_at timestamptz default now()
);

-- Notes
create table if not exists notes (
  id text primary key,
  content text,
  color text,
  timestamp timestamptz,
  is_locked boolean
);

-- Freight Analyses
create table if not exists freight_analyses (
  id text primary key,
  created_at timestamptz default now(),
  client_name text,
  cnpj text,
  origin text,
  destination text,
  service_type text,
  total_km numeric,
  total_value numeric,
  price_per_km numeric,
  data jsonb
);

-- Approval Requests
create table if not exists approval_requests (
  id text primary key,
  type text,
  description text,
  value numeric,
  requester text,
  date date,
  status text,
  justification text,
  created_at timestamptz default now()
);

-- Eco Sites
create table if not exists eco_sites (
  id text primary key,
  title text,
  url text,
  created_at timestamptz default now()
);

-- Compliance Records
create table if not exists compliance_records (
  id text primary key,
  created_at timestamptz default now(),
  title text,
  type text,
  severity text,
  status text,
  description text,
  observation text,
  date date,
  responsible text,
  involved_person text,
  attachments jsonb
);

-- Mobile Menus
create table if not exists mobile_menus (
  id text primary key,
  title text,
  subtitle text,
  footer_text text,
  items jsonb,
  created_at timestamptz default now()
);

-- Enable RLS
alter table profiles enable row level security;
alter table financial_records enable row level security;
alter table calendar_events enable row level security;
alter table vehicles enable row level security;
alter table maintenance_tasks enable row level security;
alter table notes enable row level security;
alter table freight_analyses enable row level security;
alter table approval_requests enable row level security;
alter table eco_sites enable row level security;
alter table compliance_records enable row level security;
alter table mobile_menus enable row level security;

-- Policies
do $$
begin
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'profiles') then
    create policy "Enable all access for all users" on profiles for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'financial_records') then
    create policy "Enable all access for all users" on financial_records for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'calendar_events') then
    create policy "Enable all access for all users" on calendar_events for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'vehicles') then
    create policy "Enable all access for all users" on vehicles for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'maintenance_tasks') then
    create policy "Enable all access for all users" on maintenance_tasks for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'notes') then
    create policy "Enable all access for all users" on notes for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'freight_analyses') then
    create policy "Enable all access for all users" on freight_analyses for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'approval_requests') then
    create policy "Enable all access for all users" on approval_requests for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'eco_sites') then
    create policy "Enable all access for all users" on eco_sites for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'compliance_records') then
    create policy "Enable all access for all users" on compliance_records for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where policyname = 'Enable all access for all users' and tablename = 'mobile_menus') then
    create policy "Enable all access for all users" on mobile_menus for all using (true) with check (true);
  end if;
end $$;
